language: go

go:
  - 1.12.5

env:
  - GO111MODULE=on

install: true

before_script:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint
  - go get -u github.com/goreleaser/goreleaser

script:
  - golangci-lint run
  - go test -v -race ./...

after_success:
  - goreleaser